export const PRODUCT_TYPE_OPTIONS = [
  { value: "live_plant", label: "Live Plant" },
  { value: "seed", label: "Seed" },
  { value: "bulb", label: "Bulb" },
  { value: "pot", label: "Pot" },
  { value: "planter", label: "Planter" },
  { value: "soil", label: "Soil" },
  { value: "fertilizer", label: "Fertilizer" },
  { value: "tool", label: "Tool" },
  { value: "combo", label: "Combo / Bundle" },
  { value: "gift_kit", label: "Gift Kit" },
  { value: "subscription", label: "Subscription" },
];

export const CATEGORY_OPTIONS = [
  "XL Plants",
  "Indoor Plants",
  "Flowering Plants",
  "Low Maintenance Plants",
  "Air Purifying Plants",
  "Low Light Plants",
  "Cacti and Succulents",
  "Hanging Plants",
  "Medicinal & Aromatic Plants",
  "Flower Seeds",
  "Vegetable Seeds",
  "Microgreen Seeds",
  "Herb Seeds",
  "Flower Bulbs",
  "Fruit Seeds",
  "Tree & Grass Seeds",
  "Seed Kits",
  "Plastic Pots",
  "Ceramic Pots",
  "Metal Planters",
  "Wooden Planters",
  "3D Printed Pots",
  "Hanging Planters",
  "Plant Stands",
  "Seedling Trays",
  "Basket Planters",
  "Pet-Friendly Plants",
  "Fruit Plants",
  "Bundles",
  "New Arrivals",
];
