export const PRODUCT_TYPE_OPTIONS = [
  { value: "live_plant", label: "Live Plant" },
  { value: "seed", label: "Seed" },
  { value: "bulb", label: "Bulb" },
  { value: "pot", label: "Pot" },
  { value: "planter", label: "Planter" },
  { value: "soil", label: "Soil" },
  { value: "fertilizer", label: "Fertilizer" },
  { value: "tool", label: "Tool" },
  { value: "combo", label: "Combo / Bundle" },
  { value: "gift_kit", label: "Gift Kit" },
  { value: "subscription", label: "Subscription" },
];

export const CATALOG_CATEGORY_OPTIONS = [
  { key: "indoor-plants", label: "Indoor Plants", section: "Indoor" },
  { key: "low-light-plants", label: "Low Light Plants", section: "Indoor" },
  {
    key: "low-maintenance-plants",
    label: "Low Maintenance Plants",
    section: "Indoor",
  },
  {
    key: "air-purifying-plants",
    label: "Air Purifying Plants",
    section: "Indoor",
  },
  { key: "pet-friendly-plants", label: "Pet-Friendly Plants", section: "Indoor" },
  { key: "hanging-plants", label: "Hanging Plants", section: "Indoor" },
  { key: "cacti-succulents", label: "Cacti and Succulents", section: "Indoor" },
  {
    key: "medicinal-aromatic-plants",
    label: "Medicinal & Aromatic Plants",
    section: "Indoor",
  },
  { key: "bonsai-plants", label: "Bonsai Plants", section: "Indoor" },
  { key: "rare-exotic-plants", label: "Rare & Exotic Plants", section: "Indoor" },
  { key: "xl-plants", label: "XL Plants", section: "Indoor" },
  { key: "outdoor-plants", label: "Outdoor Plants", section: "Outdoor" },
  { key: "flowering-plants", label: "Flowering Plants", section: "Outdoor" },
  { key: "fruit-plants", label: "Fruit Plants", section: "Outdoor" },
  { key: "herb-plants", label: "Herb Plants", section: "Outdoor" },
  {
    key: "edible-garden-plants",
    label: "Edible Garden Plants",
    section: "Outdoor",
  },
  { key: "flower-seeds", label: "Flower Seeds", section: "Seeds & Bulbs" },
  { key: "vegetable-seeds", label: "Vegetable Seeds", section: "Seeds & Bulbs" },
  { key: "herb-seeds", label: "Herb Seeds", section: "Seeds & Bulbs" },
  { key: "microgreen-seeds", label: "Microgreen Seeds", section: "Seeds & Bulbs" },
  { key: "fruit-seeds", label: "Fruit Seeds", section: "Seeds & Bulbs" },
  { key: "tree-grass-seeds", label: "Tree & Grass Seeds", section: "Seeds & Bulbs" },
  { key: "flower-bulbs", label: "Flower Bulbs", section: "Seeds & Bulbs" },
  { key: "seed-kits", label: "Seed Kits", section: "Seeds & Bulbs" },
  { key: "ceramic-pots", label: "Ceramic Pots", section: "Pots & Planters" },
  { key: "plastic-pots", label: "Plastic Pots", section: "Pots & Planters" },
  { key: "metal-planters", label: "Metal Planters", section: "Pots & Planters" },
  { key: "wooden-planters", label: "Wooden Planters", section: "Pots & Planters" },
  {
    key: "hanging-planters",
    label: "Hanging Planters",
    section: "Pots & Planters",
  },
  { key: "basket-planters", label: "Basket Planters", section: "Pots & Planters" },
  { key: "plant-stands", label: "Plant Stands", section: "Pots & Planters" },
  { key: "seedling-trays", label: "Seedling Trays", section: "Pots & Planters" },
  { key: "potting-soil", label: "Potting Soil", section: "Plant Care" },
  { key: "fertilizers", label: "Fertilizers", section: "Plant Care" },
  { key: "gardening-tools", label: "Gardening Tools", section: "Plant Care" },
  { key: "grow-accessories", label: "Grow Accessories", section: "Plant Care" },
  { key: "combo-kits", label: "Combo Kits", section: "Lifestyle" },
  { key: "gifting", label: "Gifting", section: "Lifestyle" },
  { key: "new-arrivals", label: "New Arrivals", section: "Lifestyle" },
];

export const CATEGORY_OPTIONS = CATALOG_CATEGORY_OPTIONS.map((category) => category.label);
